### ISSUE TITLE
Question about the base_model in google drive

### ISSUE THREAD

**Issue by YananGu** [qinenergy/cotta#1]
Hi, For some reason, I can't use request to download the base model from Google Drive, but I can download it by entering the Google Drive link from Chrome, and the link is "https://docs.google.com/uc?export=download&id=1t98aEuzeTL8P7Kpd5DIrCoCL21BNZUhC".  The name of the file in the link is "natural.pt.tar", how do I change it to "Standard.pt"? Can I rename it directly? Hope to get your help.

**Comment by qinenergy** [comment]
Hi, thanks for your interest in our work.

The md5sum of the cifar10 model we used is f1cfa8ace77463b294fafcec6c9933bb . You can use it to check with your downloaded file from the browser, they should be the same.

Best regards,
Qin

**Comment by YananGu** [comment]
Thanks for your replay. The code works now.  Can you tell me what the indicators  "not resetting model " and "resetting model" mean?

**Comment by qinenergy** [comment]
Resetting means restoring the model to the pre-trained weight. This indicator is inheritaged from TENT. It is not really used in our work as we consider continuous adaptation.

**Comment by qinenergy** [comment]
Yes, I will post it here when it is ready.

**Comment by YananGu** [comment]
Thanks for your patience.  I'll close the issue now
