### ISSUE TITLE
How to pre train a model in your seg experiments

### ISSUE THREAD

**Issue by sunrainyg** [qinenergy/cotta#10]
I've noticed that u used _**segformer.b5.1024x1024.city.160k.pth**_ as your pre-trained model in your segmentation experiments. I want to know how to get this model, as I want to pretrain a model for my own settings. I'll be appreciate that if u can provide codes for training this pretrained model. Thanks!

**Comment by qinenergy** [comment]
Hi, we used the model trained by Segformer authors. You can find the training script [here](https://github.com/NVlabs/SegFormer) and the models [here](https://drive.google.com/drive/folders/1GAku0G0iR9DsBxCbfENWMJ27c5lYUeQA).
