### ISSUE TITLE
Creating Segformer environment

### ISSUE THREAD

**Issue by Yussef93** [qinenergy/cotta#13]
Hi Qin, I encounter an error (Pip failed) while creating the environment for segmentation "Segformer" using conda, is it possible to re-write your environment locally again ? i.e. on your local workstation, not a cluster?

**Comment by qinenergy** [comment]
You will need to have some CUDA paths (for nvcc and others; see below from another issue) included in your environment to compile mmcv. 
```
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
```
I will add this information in the files. 
For further information on mmcv installation, please refer to their [website](https://mmcv.readthedocs.io/en/latest/get_started/installation.html).

After that, the normal pipeline shall work:
```
conda update conda
conda env create -f environment_segformer.yml
conda activate segformer
pip install -e . --user
```


--------
I fix this issue by **edit `~/.bashrc`** and add the following lines to **specify the path of CUDA**. ( **My server has multiple versions of CUDA.** )
`export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH`

_Originally posted by @lambert-x in https://github.com/open-mmlab/mmcv/issues/1055#issuecomment-850195980_

**Comment by Yussef93** [comment]
thank you for your reply ! it works now!

I have another question to be sure I understand. The final prediction for input data which you use for evaluation (IoU) is before or after you update student and teacher model ? Also can you clarify exactly which subset from ACDC do you use for adaptation and evaluation, in the code there is test, test1,test2,test3 are those your adaptation sets for each domain ?

**Comment by qinenergy** [comment]
1. data: Yes, data for the four domains are defined in local_configs/_base_/datasets/acdc_1024x1024_repeat.py
2. update: The same as classification exps: before. This saves one forward pass and do not hurt the performance. You can find the detailed procedures in mmseg/apis/test.py in function single_gpu_our

**Comment by HaihangWu** [comment]
> You will need to have some CUDA paths (for nvcc and others; see below from another issue) included in your environment to compile mmcv. Add two lines in your .bashrc (or other env file in your distribution)
> 
> ```
> export PATH=/usr/local/cuda/bin:$PATH
> export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
> ```
> 
> I will add this information in the files. For further information on mmcv installation, please refer to their [website](https://mmcv.readthedocs.io/en/latest/get_started/installation.html).
> 
> After that, the normal pipeline shall work:
> 
> ```
> conda update conda
> conda env create -f environment_segformer.yml
> conda activate segformer
> pip install -e . --user
> ```
> 
> I fix this issue by **edit `~/.bashrc`** and add the following lines to **specify the path of CUDA**. ( **My server has multiple versions of CUDA.** ) `export PATH=/usr/local/cuda/bin:$PATH export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH`
> 
> _Originally posted by @lambert-x in [open-mmlab/mmcv#1055 (comment)](https://github.com/open-mmlab/mmcv/issues/1055#issuecomment-850195980)_

Another solution is "pip install mmcv-full==1.2.7 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.7/index.html"
