### ISSUE TITLE
https://drive.qin.ee/ cannot be accessed

### ISSUE THREAD

**Issue by xinyanghuang7** [qinenergy/cotta#15]
Dear author, thank you for exposing the code. But when I want to reproduce the code of segmentation, I can't open the URL you provided. I hope you can answer my doubts. Thank you again!

**Comment by qinenergy** [comment]
Link fixed, thanks for letting us know. 
You may need a vpn for the website if you live in mainland China because of GFW.

**Comment by xinyanghuang7** [comment]
Thank you very much for your quick reply, the problem has been solved perfectly.
