### ISSUE TITLE
ModuleNotFoundError: No module named 'autoattack'

### ISSUE THREAD

**Issue by mohazzam1** [qinenergy/cotta#2]
I get this error when I run the code, Could you please send us the link to this package. I cannot find it on the internet.

**Comment by qinenergy** [comment]
Autoattack is part of the dependency from robustbench.

Please, use the conda environment provided by us:
```bash
conda env create -f environment.yml
conda activate cotta 
```
It will be solved by 
https://github.com/qinenergy/cotta/blob/e81127750c017038ccc1f37f0e21c2452cbc41a8/environment.yml#L107
