### ISSUE TITLE
 Installation of mmcv>=[1, 1, 4], <=[1, 3, 0] while using Segmentation codes 

### ISSUE THREAD

**Issue by daeunni** [qinenergy/cotta#22]
Hi, Thanks for your nice work! 

I downloaded your segmentation code `acdc-submission` which you kindly provided in the issue before. 
I successfully installed `mmcv` at cuda 11.1 + torch 1.8.0 using [this codes](https://github.com/open-mmlab/mmcv/issues/204#issuecomment-817142228) 

However, what I installed version of mmcv is **MMCV==1.7.1**. 
As a result, I got an error like below. 

`AssertionError: MMCV==1.7.1 is used but incompatible. **Please install mmcv>=[1, 1, 4], <=[1, 3, 0**].`

I searched [here](https://download.openmmlab.com/mmcv/dist/cu102/torch1.7.0/index.html) to install  `mmcv>=[1, 1, 4], <=[1, 3, 0]` version, but they don't serve a low version of mmcv for cuda 11.1. 

So how can I deal with this problem?

**Comment by daeunni** [comment]
@qinenergy  Please reply my issue if you have spare time! :) thanks a lot.

**Comment by qinenergy** [comment]
If possible, please use cuda 10.1 and mmcv 1.2.7 (and other packages listed in environment_segformer.yaml)
You can use environment.sh to setup the environment.

A pre-compiled wheel is also provided in https://drive.qin.ee/cv/cvpr2022/mmcv_full-1.2.7-cp39-cp39-linux_x86_64.whl

**Comment by daeunni** [comment]
Thanks for your reply! 
However, I think it will be difficult to use cuda 10.1 in my current environment. 
How can I use above `.whl`?  (I'm new to here TT)

**Comment by daeunni** [comment]
Or I think your segmentation codes are pretty similar to [here](https://github.com/open-mmlab/mmsegmentation), so can I use other mmcv version?

**Comment by qinenergy** [comment]
1. .whl can be installed by pip install xxx.whl . The provided wheel is compiled for cuda10 though.
2. In principle yes, our segmentation code is modified from the Segformer(https://github.com/NVlabs/SegFormer) code base. You can use newer mmcv versions, but you may need to tweak the code base a little bit. You can check the segformer Github issue page to find out more.
3. Another possibility is to compile your own mmcv or try to match other pre-compiled mmcv1.2.7 with cuda11. For example, there is 
```
mmcv_full-1.2.7+torch1.7.0+cu110-cp38-cp38-manylinux1_x86_64.whl
```
 in this [list](https://download.openmmlab.com/mmcv/dist/index.html). In the latter, you will need to change python version (to python3.8) and torch version(to 1.7) to do this.

**Comment by daeunni** [comment]
Okay! Thanks a lot. I'll try what you mentioned and let you know the result! :)
