### ISSUE TITLE
SystemExit:1 error was reported while running cifar10c

### ISSUE THREAD

**Issue by ghqshuai** [qinenergy/cotta#24]
Hello author, when I run several main programs of cifar, I will report an error SystemExit:1. Have you ever encountered such a situation?

**Comment by qinenergy** [comment]
Hi, I never encountered this error. 
Quick question, did you use the same environment with python 3.9 or are you using your own?

**Comment by ghqshuai** [comment]
Thanks for the author's quick reply. Maybe it is because I used my own environment. I will change the environment before running the code

**Comment by qinenergy** [comment]
Feel free to reopen if you still encounter the error using the provided env.
