### ISSUE TITLE
Error in loading ckpt/cifar10/corruptions/Standard.pt

### ISSUE THREAD

**Issue by mxr01** [qinenergy/cotta#25]
requests.exceptions.SSL Error: HTTPSConnectionPool ( host=‘docs. google.com' , port=443): Max retries exceeded wits url:/uc？export=download&confirm=t&id=1t98aEuzeTL8P7Kpd5DIrCoCL21BNZUhC (Caused by SSLError(SSLEOFError(8，'EOF occurred in violation of protocol ( ssl.c:1129) ')))

**Comment by mxr01** [comment]
Hello author, when running will report the above error

**Comment by qinenergy** [comment]
Hi, I reran the code locally and it is able to download Standard.pt. 
```
Download started: path=ckpt/cifar10/corruptions/Standard.pt (gdrive_id=1t98aEuzeTL8P7Kpd5DIrCoCL21BNZUhC)
Download finished: path=ckpt/cifar10/corruptions/Standard.pt (gdrive_id=1t98aEuzeTL8P7Kpd5DIrCoCL21BNZUhC)
```
Please check your internet connection if possible. If you are in a region where google is blocked, you will need to use a system-wide vpn (e.g. ciscovpn) or use [proxychains](https://github.com/haad/proxychains).

**Comment by mxr01** [comment]
Okay, thank you for your answer, is it also possible to download locally and then import?Can you provide a local download link?

**Comment by qinenergy** [comment]
You can download it here: https://drive.qin.ee/api/raw/?path=/cv/cvpr2022/Standard.pt

For other models, please follow the link below if you want to download from browser. 
https://github.com/qinenergy/cotta/issues/3#issuecomment-1156404687

**Comment by Fenghao1995** [comment]
Hello author！Could you tell me how to download Hendrycks2020AugMix_ResNeXt.pt by browser?

**Comment by qinenergy** [comment]
@Fenghao1995 You can find all model's google drive id's [here](https://github.com/RobustBench/robustbench/blob/master/robustbench/model_zoo/cifar10.py).

For the Hendrycks2020AugMix_ResNeXt.pt for cifar10, the link is https://docs.google.com/uc?export=download&id=1uGP3nZbL3LC160kOsxwkkt6tDd4qbZT1

**Comment by Fenghao1995** [comment]
Thank you so much! But I want to obtain the Hendrycks2020AugMix_ResNeXt.pt for cifar100

**Comment by qinenergy** [comment]
@Fenghao1995 Please do the same using https://github.com/RobustBench/robustbench/blob/master/robustbench/model_zoo/cifar100.py

**Comment by qinenergy** [comment]
@Fenghao1995 https://docs.google.com/uc?export=download&id=1ocnHbvDdOBLvgNr6K7vEYL08hUdkD1Rv
