### ISSUE TITLE
gaussian_noise file is missing

### ISSUE THREAD

**Issue by jayus71** [qinenergy/cotta#27]
Dear author, thank you for exposing the code. But when I run the code, I found this error: 
<img width="813" alt="image" src="https://github.com/qinenergy/cotta/assets/62584977/a079f4c9-e73e-4bda-8084-55d184ddc281">
how can I fix it?

**Comment by qinenergy** [comment]
You have a connection problem with Zenodo. I assume that you are in mainland China. The download script works for me.

![image](https://github.com/qinenergy/cotta/assets/9915021/b7a36212-9384-46c8-9cf6-cba9c1f491c2)

Please check your internet connection if possible. If you are in a region where google is blocked, you will need to use a system-wide vpn (e.g. ciscovpn) or use [proxychains](https://github.com/haad/proxychains).

**Comment by jayus71** [comment]
Sorry to bother you again. I do have the vpn. I check the code again, and I found when the dir data exists, the download script would not work, after I delete the dir, it works again.
thank you again!
