### ISSUE TITLE
Semantic segmentation experiments

### ISSUE THREAD

**Issue by SnowdenLee** [qinenergy/cotta#6]
Hello, will you also upload scripts for Cityscapes-to-ACDC experiments? Thanks a lot!

**Comment by qinenergy** [comment]
Thanks for your interest on our work. 
You can find the segmentation code [here](https://drive.qin.ee/api/raw/?path=/cv/cvpr2022/acdc-seg.tar.gz).

**Comment by lixiang007666** [comment]
This link cannot be accessed now, can you fix it? @qinenergy

**Comment by qinenergy** [comment]
@lixiang007666 back online now. Thanks for the notification.

**Comment by lixiang007666** [comment]
> @lixiang007666 back online now. Thanks for the notification.

Thanks！！！

**Comment by chenln863-crypto** [comment]
This link cannot be accessed now, can you fix it? @qinenergy

**Comment by 1759906031** [comment]
This link cannot be accessed now, could you fix it? @qinenergy

**Comment by qinenergy** [comment]
Renewed my M365 subscription just now, data should be available again now. @1759906031 @chenln863-crypto
