### ISSUE TITLE
Questions around code and paper

### ISSUE THREAD

**Issue by ShambhaviCodes** [qinenergy/cotta#7]
Hi,

Thanks for patiently answering all the questions in previous issues. The paper is interesting, congratulations! I had a few questions and it would be great if you could help me understand this better :
1. Which model is being used for evaluation? The model running on severity 5, has it already learnt/updated from all previous severities? When you move from one corruption to next while evaluating, has the model learnt from the last one or has it been tested individually on each corruption?
2. In each batch, is there only one severity and one corruption?

**Comment by qinenergy** [comment]
Hi, thanks for your interest in our work!

1. a> 
>     Which model is being used for evaluation? 
The model is evaluated on the fly during test time. As soon as a new batch is fed, the model makes the final prediction for that specific batch, and applies the gradient to that model. The prediction and learning step can be found here:
https://github.com/qinenergy/cotta/blob/6773364c651a005e401fdedf9e028bac5019b178/cifar/cotta.py#L95
    b> 
>     The model running on severity 5, has it already learnt/updated from all previous severities?
For all severity 5 experiments (Table 2,4,6), we consider only one severity. Therefore, no data from other severity levels is used. 
         The only exception is for the gradual experiment in Table 3 in the paper, where the severity does change in the sequence. That change is defined in https://github.com/qinenergy/cotta/blob/6773364c651a005e401fdedf9e028bac5019b178/cifar/cifar10c_gradual.py#L51
    c> 
>     When you move from one corruption to next while evaluating, has the model learnt from the last one or has it been tested individually on each corruption? 
Yes, when evaluated on later corruption types in a evaluation sequence, the model has already learnt from past corruption types. The sequence is defined in the setup yaml files. This continual adaptation is also the key difference between our setup and TENT's.
https://github.com/qinenergy/cotta/blob/6773364c651a005e401fdedf9e028bac5019b178/cifar/cfgs/cifar10/cotta.yaml#L10
2. 
>     In each batch, is there only one severity and one corruption?
 Yes. Data in the same batch comes from the same severity and corruption.

Hope this can help!

**Comment by ZDstandup** [comment]
Hi authors, thanks for sharing the code. I have studied the paper and the code. I had a question and it would be great if you could help me understand this better.
In the paper, the student model is treated as the main model. Why do you use the prediction of the teacher model as the final prediction of the test sample? Thanks in advance!

**Comment by qinenergy** [comment]
@ZDstandup Hi, as mentioned in the paper, the teacher model prediction is used for the final prediction.
```
in Algorithm 1: Output: Prediction f_θ′^t(x_t); Updated teacher model fθ′^{t+1}(x).
on Page5Line1: Our final prediction for the input data x_t^T is the class with the highest probability in \hat{y'_t^′T}. 
## θ' and y' with the  '  correspond again to the teacher model and teacher model's prediction in the paper.
```
The reason of using the teacher to give final prediction is also provided on Page5Line7 after the defining the final output. 

I can summarize them here. In short, there are two reasons:
1. We observe that teacher model's pseudolabel is often more precise than the student's. This is consistent with the observsation from the MeanTeacher paper. We should then of course use the more accurate one for final prediction.
2. We observe that the teacher's prediction is more robust to domain changes. The mean teacher prediction encodes the information from models in past iterations and is, therefore, less likely to suffer from catastrophic forgetting in long-term continual adaptation and improve the generalization capability to new unseen domains.

**Comment by ZDstandup** [comment]
@qinenergy, Hi, Thank you very much for the quick and detailed reply, which helps me a lot. Wish you happy every day.
